# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5a4e988198a185d6d4dfbc51f73220e249853cc8fbe705c2ff7449583a8e32d2f1e32955d2bfc5603ffcdf6db1342685498602f05051b7d0ffbb76cb1dcfac8
  sms_ru_api_id:
  robokassa_login:
  robokassa_first_password:
  robokassa_second_password:

test:
  secret_key_base: 1d2a02250fe2450c5f0079c2f1a6cb4107cf0ca3de91933d3833526df7de695a76b440ddf2c8bf0c6526a3f89287e108106db178d5d2f448808d82b103fa656b
  sms_ru_api_id:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sms_ru_api_id: <%= ENV["SMS_RU_API_ID"] %>
  robokassa_login: <%= ENV["ROBOKASSA_LOGIN"] %>
  robokassa_first_password: <%= ENV["ROBOKASSA_FIRST_PASSWORD"] %>
  robokassa_second_password: <%= ENV["ROBOKASSA_SECOND_PASSWORD"] %>
  robokassa_mode: <%= ENV["ROBOKASSA_MODE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
